name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  release:
    runs-on: windows-2022
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.0

      - name: Configure and build the project
        uses: threeal/cmake-action@v2.0.0

      - name: Configure and build the project with examples
        uses: threeal/cmake-action@v2.0.0
        with:
          options: BUILD_EXAMPLE=ON
