name: build
on:
  workflow_dispatch:
  push:
jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: Configure CMake
        run: cmake . -B build

      - name: Build targets
        run: cmake --build build

      - name: Reconfigure CMake to build the examples
        run: cmake . -B build -DBUILD_EXAMPLE=ON

      - name: Rebuild targets
        run: cmake --build build

  test:
    runs-on: windows-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: Configure CMake
        run: cmake . -B build -DBUILD_TESTING=ON -DCMAKE_CXX_FLAGS='/WX'

      - name: Build targets
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --verbose
