name: test
on:
  workflow_dispatch:
  push:
jobs:
  unit-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0

      - name: Configure CMake
        run: cmake . -B build -DBUILD_TESTING=ON

      - name: Build targets
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --verbose

  check-warning:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0

      - name: Configure CMake
        run: cmake . -B build -DCMAKE_CXX_FLAGS='/WX' -DBUILD_TESTING=ON

      - name: Build targets
        run: cmake --build build
