name: test
on:
  workflow_dispatch:
  push:
jobs:
  unit-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0

      - name: Configure CMake
        run: cmake . -B build -DBUILD_TESTING=ON

      - name: Build targets
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --verbose

  check-warning:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0

      - name: Configure CMake
        run: cmake . -B build -DCMAKE_CXX_FLAGS='/WX' -DBUILD_TESTING=ON

      - name: Build targets
        run: cmake --build build

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0

      - name: Install cmake-format
        run: pip3 install cmake-format

      - name: Configure CMake
        run: cmake . -B build

      - name: Check code formatting
        run: |
          cmake --build build --target format
          cmake --build build --target check-format
