name: test
on:
  workflow_dispatch:
  pull_request:
    branches: ['*', '!latest']
  push:
    branches: [latest, main]
jobs:
  unit-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.1

      - name: Configure, build, and test the project
        uses: threeal/cmake-action@v1.3.0
        with:
          options: BUILD_TESTING=ON
          run-test: true

      - name: Checkout the CI sound helpers repository
        uses: actions/checkout@v4.1.1
        with:
          repository: LABSN/sound-ci-helpers
          path: sound

      - name: Setup sound devices
        run: |
          net start audiosrv
          powershell sound/windows/setup_sound.ps1

      - name: Configure, build, and test the project with sound devices support
        uses: threeal/cmake-action@v1.3.0
        with:
          options: TESTING_INPUTS_COUNT=1 TESTING_OUTPUTS_COUNT=1
          run-test: true

  check-warning:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.1

      - name: Configure and build the project
        uses: threeal/cmake-action@v1.3.0
        with:
          cxx-flags: /WX
          options: BUILD_TESTING=ON TESTING_INPUTS_COUNT=1 TESTING_OUTPUTS_COUNT=1
          run-build: true

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Configure and build the project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          build-args: --target fix-format

      - name: Check diff
        run: git diff --exit-code HEAD
