name: test
on:
  workflow_dispatch:
  push:
jobs:
  unit-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Configure CMake
        run: cmake . -B build -DBUILD_TESTING=ON

      - name: Build targets
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      - name: Checkout CI sound helpers repository
        uses: actions/checkout@v3.3.0
        with:
          repository: LABSN/sound-ci-helpers
          path: sound

      - name: Setup sound devices
        run: |
          net start audiosrv
          powershell sound/windows/setup_sound.ps1

      - name: Reconfigure CMake
        run: cmake build -DTESTING_INPUTS_COUNT=1 -DTESTING_OUTPUTS_COUNT=1

      - name: Rebuild targets
        run: cmake --build build

      - name: Rerun tests
        run: ctest --test-dir build --output-on-failure

  check-warning:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Configure CMake
        run: cmake . -B build -DCMAKE_CXX_FLAGS='/WX' -DBUILD_TESTING=ON -DTESTING_INPUTS_COUNT=1 -DTESTING_OUTPUTS_COUNT=1

      - name: Build targets
        run: cmake --build build

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Install cmake-format
        run: pip3 install cmake-format

      - name: Configure CMake
        run: cmake . -B build

      - name: Check code formatting
        run: |
          cmake --build build --target format
          cmake --build build --target check-format
