name: test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  unit-tests:
    runs-on: windows-2022
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.0

      - name: Configure and build the project
        uses: threeal/cmake-action@v2.0.0
        with:
          options: VOLUME_ENABLE_TESTS=ON

      - name: Test the project
        uses: threeal/ctest-action@v1.1.0

      - name: Checkout the CI sound helpers repository
        uses: actions/checkout@v4.2.0
        with:
          repository: LABSN/sound-ci-helpers
          path: sound

      - name: Setup sound devices
        run: |
          net start audiosrv
          powershell sound/windows/setup_sound.ps1

      - name: Configure and build the project with sound devices support
        uses: threeal/cmake-action@v2.0.0
        with:
          options:
            TESTING_INPUTS_COUNT=1
            TESTING_OUTPUTS_COUNT=1

      - name: Test the project with sound devices support
        uses: threeal/ctest-action@v1.1.0

  check-warning:
    runs-on: windows-2022
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.0

      - name: Configure and build the project
        uses: threeal/cmake-action@v2.0.0
        with:
          cxx-flags: /WX
          options:
            VOLUME_ENABLE_TESTS=ON
            TESTING_INPUTS_COUNT=1
            TESTING_OUTPUTS_COUNT=1

  check-formatting:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Install cmakelang
        uses: threeal/pipx-install-action@v1.0.0
        with:
          packages: cmakelang

      - name: Configure and build the project
        uses: threeal/cmake-action@v2.0.0
        with:
          build-args: --target fix-format

      - name: Check diff
        run: git diff --exit-code HEAD
